/* ============================================================
   quotes.js — 500 Motivational Quotes
   Categories: Discipline, Health, Habits, Mindset, Progress,
   Self-Care, Strength, Goals, Persistence, Affirmations
   ============================================================ */

const Quotes = (() => {
  const ALL = [
    // ── DISCIPLINE & CONSISTENCY (1-50) ──────────────────────
    "Discipline is choosing between what you want now and what you want most.",
    "Small daily improvements over time lead to stunning results.",
    "Success is the sum of small efforts repeated day in and day out.",
    "We are what we repeatedly do. Excellence is not an act, but a habit.",
    "The secret of getting ahead is getting started.",
    "Motivation gets you going. Discipline keeps you growing.",
    "You will never always be motivated. Learn to be disciplined.",
    "Discipline is the bridge between goals and accomplishment.",
    "The pain of discipline is nothing like the pain of disappointment.",
    "Discipline equals freedom.",
    "Self-discipline is self-love.",
    "Each day you must choose: the pain of discipline or the pain of regret.",
    "Consistency is what transforms average into excellence.",
    "It's not about being the best. It's about being better than yesterday.",
    "Success isn't always about greatness. It's about consistency.",
    "You don't need to be extreme, just consistent.",
    "Repetition is the mother of skill.",
    "Consistency over intensity.",
    "Show up every day. That's the secret.",
    "Don't break the chain.",
    "How you do one thing is how you do everything.",
    "The successful person has the habit of doing things failures don't like to do.",
    "Suffer the pain of discipline or suffer the pain of regret.",
    "Discipline is remembering what you want.",
    "Your daily routine determines your success.",
    "You don't need motivation every day. You need discipline every day.",
    "Success doesn't come from what you do occasionally. It comes from what you do consistently.",
    "Make each day your masterpiece.",
    "Be so busy improving yourself that you have no time to criticize others.",
    "The compound effect is the principle of reaping huge rewards from small choices.",
    "One percent better every day.",
    "Results happen over time, not overnight. Work hard, stay consistent, and be patient.",
    "Routine is the foundation of freedom.",
    "You are your habits.",
    "Build systems, not just goals.",
    "The secret of your future is hidden in your daily routine.",
    "Success is not a destination but a habit.",
    "Your current habits are perfectly designed to deliver your current results.",
    "Habits are the compound interest of self-improvement.",
    "What you do every day matters more than what you do once in a while.",
    "You'll never change your life until you change something you do daily.",
    "The chains of habit are too light to be felt until they are too heavy to be broken.",
    "Good habits are the key to all success.",
    "Make it so easy you can't say no.",
    "Every action you take is a vote for the type of person you wish to become.",
    "We don't rise to the level of our goals. We fall to the level of our systems.",
    "Your net worth to the world is usually determined by what remains after bad habits are subtracted from good ones.",
    "Motivation is a muscle. Flex it daily.",
    "Discipline is not punishment. It is self-respect.",
    "You already have everything you need to start.",

    // ── HEALTH & WELLNESS (51-100) ───────────────────────────
    "The greatest wealth is health.",
    "Take care of your body. It's the only place you have to live.",
    "A healthy outside starts from the inside.",
    "Your health is an investment, not an expense.",
    "Movement is medicine.",
    "The first wealth is health.",
    "Physical fitness is the first requisite of happiness.",
    "Respect your body. It's the only one you get.",
    "Eat well. Move daily. Hydrate often. Sleep enough. Love your body.",
    "He who has health has hope, and he who has hope has everything.",
    "Your body hears everything your mind says. Stay positive.",
    "A fit body is the temple that houses the mind.",
    "Wellness is the complete integration of body, mind, and spirit.",
    "The groundwork for all happiness is good health.",
    "Health is not valued till sickness comes.",
    "A healthy attitude is contagious.",
    "Getting healthy is about so much more than losing weight.",
    "Love yourself enough to live a healthy lifestyle.",
    "Being healthy and fit isn't a fad or a trend. It's a lifestyle.",
    "The body achieves what the mind believes.",
    "Your body is a reflection of your lifestyle.",
    "Health is a relationship between you and your body.",
    "A healthy life is a wealthy life.",
    "The greatest gift you can give your family is a healthy you.",
    "Make your health a priority, not an option.",
    "Nourish your mind, body, and soul.",
    "When diet is wrong, medicine is of no use. When diet is correct, medicine is of no need.",
    "Health is the crown on the well person's head that only the ill person can see.",
    "Your health account and your bank account are the same thing. The more you put in, the more you can take out.",
    "The body is the servant of the mind.",
    "Don't sacrifice your health for anything.",
    "A healthy heart is a thankful heart.",
    "Every healthy choice counts.",
    "Fall in love with taking care of yourself.",
    "When you eat well and exercise, you're telling your body you love it.",
    "Health looks different on everyone.",
    "The food you eat can be either the safest form of medicine, or the slowest form of poison.",
    "Physical activity is the best way to improve mental health.",
    "The wise person considers health the greatest of human blessings.",
    "Happiness is the highest form of health.",
    "Your mental health is just as important as your physical health.",
    "Don't let the scale define you.",
    "Numbers on a scale don't define your worth.",
    "You are so much more than a number.",
    "Weight is just one piece of the puzzle.",
    "The doctor of the future will cure and prevent disease with nutrition.",
    "Sleep is the best meditation.",
    "Not all storms come to disrupt your life; some come to clear your path.",
    "A good laugh and a long sleep are the two best cures for anything.",
    "Hydrate or diedrate.",

    // ── MINDSET & ATTITUDE (101-150) ─────────────────────────
    "Whether you think you can or you think you can't, you're right.",
    "The mind is everything. What you think, you become.",
    "Your limitation—it's only your imagination.",
    "Believe you can and you're halfway there.",
    "What you focus on grows.",
    "Train your mind to see the good in every situation.",
    "Rule your mind or it will rule you.",
    "Mindset is everything.",
    "One small positive thought can change your whole day.",
    "I am not a product of my circumstances. I am a product of my decisions.",
    "What consumes your mind controls your life.",
    "The greatest discovery is that a person can alter their life by altering their attitude.",
    "Your attitude determines your direction.",
    "We become what we think about most of the time.",
    "Think positive. Be positive.",
    "Inhale confidence, exhale doubt.",
    "Don't be pushed by your fears. Be led by your dreams.",
    "Stop being afraid of what could go wrong and start being excited about what could go right.",
    "The only impossible journey is the one you never begin.",
    "Everything is hard before it is easy.",
    "In the middle of difficulty lies opportunity.",
    "If you change the way you look at things, the things you look at change.",
    "Where focus goes, energy flows.",
    "A positive attitude gives you power over your circumstances.",
    "Life is 10% what happens to us and 90% how we react to it.",
    "Clear your mind of can't.",
    "Don't let a bad day make you feel like you have a bad life.",
    "Replace 'I have to' with 'I get to.'",
    "Your mind is a garden. Your thoughts are the seeds. You can grow flowers or weeds.",
    "Be a warrior, not a worrier.",
    "Optimism is a happiness magnet.",
    "Every morning we are born again. What we do today matters most.",
    "The comeback is always stronger than the setback.",
    "Stars can't shine without darkness.",
    "Not every day is good, but there is good in every day.",
    "What seems impossible today will one day become your warm-up.",
    "You can't control the wind, but you can adjust your sails.",
    "If you hear a voice that says you cannot paint, then by all means paint, and that voice will be silenced.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Stop looking for happiness in the same place you lost it.",
    "You already survived 100% of your worst days.",
    "A diamond is a chunk of coal that did well under pressure.",
    "When you want to succeed as bad as you want to breathe, then you'll be successful.",
    "Your body can stand almost anything. It's your mind you have to convince.",
    "Courage is not the absence of fear but the triumph over it.",
    "Be the energy you want to attract.",
    "Tension is who you think you should be. Relaxation is who you are.",
    "When everything seems against you, remember the airplane takes off against the wind.",
    "Fear is just excitement in need of an attitude adjustment.",
    "Motion creates emotion.",

    // ── PROGRESS & GROWTH (151-200) ──────────────────────────
    "Progress, not perfection.",
    "Strive for progress, not perfection.",
    "A little progress each day adds up to big results.",
    "Slow progress is still progress.",
    "Your speed doesn't matter. Forward is forward.",
    "Progress is progress, no matter how small.",
    "It's a slow process, but quitting won't speed it up.",
    "Every step matters.",
    "Rome wasn't built in a day, but they were laying bricks every hour.",
    "Small steps every day.",
    "The journey of a thousand miles begins with a single step.",
    "Sometimes the smallest step in the right direction ends up being the biggest step of your life.",
    "Don't wait for extraordinary opportunities. Seize common occasions and make them great.",
    "What you're doing today is getting you closer to where you want to be tomorrow.",
    "Just keep swimming.",
    "Inch by inch, it's a cinch. Yard by yard, it's hard.",
    "Every flower must grow through dirt.",
    "Just because you can't see results doesn't mean they aren't happening.",
    "Growth begins at the end of your comfort zone.",
    "Comfort zones are beautiful places, but nothing ever grows there.",
    "The biggest room in the world is the room for improvement.",
    "Don't just go through it. Grow through it.",
    "It never gets easier. You just get stronger.",
    "Transformation is not a future event. It is a present activity.",
    "Self-improvement is a lifelong journey.",
    "Be patient with yourself. Self-growth is tender. It's holy ground.",
    "Today's accomplishments were yesterday's impossibilities.",
    "Every accomplishment starts with the decision to try.",
    "What we achieve inwardly will change outer reality.",
    "Change happens at the end of your comfort zone.",
    "The only way out is through.",
    "Growth is growth, no matter how slow.",
    "Be willing to be a beginner every single morning.",
    "Life begins at the end of your comfort zone.",
    "In any given moment, we have two options: step forward into growth or step back into safety.",
    "We cannot become what we want by remaining what we are.",
    "It takes courage to grow up and become who you really are.",
    "Who you become in the process matters more than the outcome.",
    "Great things take time. Be patient.",
    "Three months from now you will thank yourself.",
    "Six months of hard work can put you five years ahead.",
    "Imagine where you'd be if you started a year ago.",
    "The earlier you start working on something, the earlier you'll see results.",
    "Today is a new day to start fresh.",
    "Every day is a second chance.",
    "New day. New strength. New thoughts.",
    "Little things make big days.",
    "Small improvements compound over time.",
    "Celebrate every tiny victory.",
    "Give yourself some credit. You've come further than you think.",

    // ── PERSISTENCE & GRIT (201-250) ─────────────────────────
    "It always seems impossible until it's done.",
    "Fall seven times, stand up eight.",
    "The only guarantee of failure is to quit.",
    "Never let a stumble in the road be the end of the journey.",
    "If you get tired, learn to rest, not to quit.",
    "Champions keep playing until they get it right.",
    "Winners are not people who never fail but people who never quit.",
    "Don't stop until you're proud.",
    "The harder the battle, the sweeter the victory.",
    "Keep going. Everything you need will come at the perfect time.",
    "A river cuts through rock not because of its power, but its persistence.",
    "Persistence guarantees that results are inevitable.",
    "It does not matter how slowly you go as long as you do not stop.",
    "The difference between a stumbling block and a stepping stone is how high you raise your foot.",
    "Energy and persistence conquer all things.",
    "You may have to fight a battle more than once to win it.",
    "Our greatest glory is not in never falling, but in rising every time we fall.",
    "Tough times never last, but tough people do.",
    "If you're going through hell, keep going.",
    "The only bad workout is the one that didn't happen.",
    "Run when you can. Walk if you have to. Crawl if you must. Just never give up.",
    "Every champion was once a contender who refused to give up.",
    "You haven't failed until you quit trying.",
    "Rest if you must, but don't you quit.",
    "Grit is living life like it's a marathon, not a sprint.",
    "Don't quit. You're already in pain. Get a reward from it.",
    "Dead last finish is greater than did not finish, which trumps did not start.",
    "The struggle you're in today is developing the strength you need for tomorrow.",
    "When you feel like quitting, think about why you started.",
    "Every setback is a setup for a comeback.",
    "Rock bottom will teach you lessons that mountain tops never will.",
    "Sometimes you win. Sometimes you learn.",
    "Failure is simply the opportunity to begin again, more intelligently.",
    "Mistakes are proof that you are trying.",
    "The master has failed more times than the beginner has even tried.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "If you stumble, make it part of the dance.",
    "Don't be afraid to start over. This time you're starting from experience.",
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "Life rewards the persistent.",
    "The successful warrior is the average person with laser-like focus.",
    "Stay patient and trust your journey.",
    "Keep showing up.",
    "Trust the process.",
    "Hold the vision. Trust the process.",
    "Results take time. Don't give up.",
    "Stay dedicated. It's not going to happen overnight.",
    "Success is not overnight. It's when every day you get a little better.",
    "Good things take time.",
    "The road to success is always under construction.",

    // ── GOALS & ACTION (251-300) ─────────────────────────────
    "A goal without a plan is just a wish.",
    "Setting goals is the first step in turning the invisible into the visible.",
    "Goals are dreams with deadlines.",
    "The distance between your dreams and reality is called action.",
    "Dream it. Believe it. Build it.",
    "Don't decrease the goal. Increase the effort.",
    "Set a goal that makes you want to jump out of bed in the morning.",
    "Set some goals, then demolish them.",
    "Your goals don't care how you feel.",
    "If plan A doesn't work, the alphabet has 25 more letters.",
    "If the plan doesn't work, change the plan, but never the goal.",
    "Take the risk or lose the chance.",
    "The way to get started is to quit talking and begin doing.",
    "Action is the foundational key to all success.",
    "Action is the antidote to despair.",
    "Well done is better than well said.",
    "Think less. Do more.",
    "Done is better than perfect.",
    "Stop wishing and start doing.",
    "You don't get what you wish for. You get what you work for.",
    "Dare to begin.",
    "Stop overthinking. Start doing.",
    "Decide. Commit. Succeed.",
    "Don't talk. Just act. Don't say. Just show. Don't promise. Just prove.",
    "If not now, when?",
    "Sometimes later becomes never. Do it now.",
    "Don't wait. The time will never be just right.",
    "There are seven days in a week, and someday isn't one of them.",
    "The first step is the hardest. After that, it's just one foot in front of the other.",
    "Knowing is not enough; we must apply. Wishing is not enough; we must do.",
    "What you do today can improve all your tomorrows.",
    "You are one decision away from a completely different life.",
    "Motivation follows action. Start first.",
    "The only time you should look back is to see how far you've come.",
    "Create your own sunshine.",
    "Be the change you wish to see in the world.",
    "If something stands between you and your success, move it.",
    "Go the extra mile. It's never crowded there.",
    "Opportunities don't happen. You create them.",
    "Don't find fault, find a remedy.",
    "Do what you can with all you have, wherever you are.",
    "Start where you are. Use what you have. Do what you can.",
    "Every day brings new choices.",
    "The best time to start was yesterday. The next best time is now.",
    "Take action. An inch of movement will bring you closer to your goals.",
    "Dream bigger. Do bigger.",
    "Don't wish for it. Work for it.",
    "Do something today that your future self will thank you for.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Your future is created by what you do today, not tomorrow.",

    // ── STRENGTH & POWER (301-350) ───────────────────────────
    "You are stronger than you think.",
    "Strength does not come from winning. Your struggles develop your strengths.",
    "Where there is no struggle, there is no strength.",
    "Strength grows in the moments when you think you can't go on but keep going anyway.",
    "You have within you right now everything you need to deal with whatever the world throws at you.",
    "What doesn't kill you makes you stronger.",
    "Be so good they can't ignore you.",
    "Hard work beats talent when talent doesn't work hard.",
    "Push yourself because no one else is going to do it for you.",
    "Be stronger than your strongest excuse.",
    "Once you control your mind, you can conquer your body.",
    "When life gets harder, challenge yourself to be stronger.",
    "The world breaks everyone, and afterward some are strong at the broken places.",
    "Strength is the product of struggle.",
    "You have the power to create change.",
    "You were given this life because you are strong enough to live it.",
    "Be relentless.",
    "No one is you, and that is your superpower.",
    "Be fierce. Be kind. Be unstoppable.",
    "You define your own limits.",
    "Limits exist only in the mind.",
    "Look in the mirror. That's your competition.",
    "Compete with yourself, not others.",
    "Be the hero of your own story.",
    "You don't need anyone's permission to be great.",
    "The only person you should try to be better than is who you were yesterday.",
    "You are the CEO of your own life.",
    "You are the architect of your own destiny.",
    "I am deliberate and afraid of nothing.",
    "Go confidently in the direction of your dreams.",
    "Don't shrink. Stand your sacred ground.",
    "You were born to be real, not to be perfect.",
    "Be brave enough to be bad at something new.",
    "Be fearless in the pursuit of what sets your soul on fire.",
    "Great things never come from comfort zones.",
    "Get comfortable being uncomfortable.",
    "If it doesn't challenge you, it won't change you.",
    "Comfort is the enemy of progress.",
    "The pain you feel today will be the strength you feel tomorrow.",
    "Today's pain is tomorrow's power.",
    "Sore today, strong tomorrow.",
    "No pain, no gain. No guts, no glory.",
    "You can have results or excuses, not both.",
    "Excuses don't burn calories.",
    "No excuses. Just results.",
    "Don't stop when you're tired. Stop when you're done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Rise and grind.",
    "Hustle until you no longer need to introduce yourself.",
    "Put in the work. Watch what happens.",

    // ── SELF-CARE & SELF-WORTH (351-400) ─────────────────────
    "You can't pour from an empty cup. Take care of yourself first.",
    "Self-care is not self-indulgence. Self-care is self-preservation.",
    "Make yourself a priority once in a while. It's not selfish, it's necessary.",
    "You owe yourself the love that you so freely give to other people.",
    "You deserve to be healthy and happy.",
    "You are enough just as you are.",
    "Be gentle with yourself, you're doing the best you can.",
    "Speak to yourself like someone you love.",
    "You are worthy of the goals you set.",
    "Don't be a victim of negative self-talk.",
    "Believe in yourself and all that you are.",
    "A strong positive self-image is the best possible preparation for success.",
    "You are not your mistakes.",
    "You are allowed to be both a masterpiece and a work in progress.",
    "Be kind to your mind.",
    "Healing takes time. And that's okay.",
    "Healing is not linear.",
    "Be patient with yourself. Nothing in nature blooms all year.",
    "It's okay to not be okay, but it's not okay to stay that way.",
    "Give yourself permission to grow at your own pace.",
    "Give yourself permission to be happy.",
    "Stop poisoning yourself with negative thoughts about your body.",
    "Feeling good about yourself isn't a luxury. It's a necessity.",
    "The privilege of a lifetime is being who you are.",
    "Don't compromise yourself. You are all you've got.",
    "Respect yourself enough to walk away from anything that no longer serves you.",
    "In a world where you can be anything, be kind to yourself.",
    "The most powerful relationship you will ever have is the relationship with yourself.",
    "You deserve the love you keep trying to give everyone else.",
    "Comparison is the thief of joy.",
    "Don't compare your chapter one to someone else's chapter twenty.",
    "Your journey is unique and beautiful.",
    "You are more capable than you know.",
    "Your value doesn't decrease based on someone's inability to see your worth.",
    "You were not born to just pay bills and die.",
    "Let go of who you think you're supposed to be; embrace who you are.",
    "Recovery is part of the process.",
    "Rest days are growth days.",
    "Some days are just meant for resting and recovering.",
    "There is no shame in taking a break.",
    "The soul always knows what to do to heal itself. The challenge is to silence the mind.",
    "Nourishing yourself in a way that helps you blossom is attainable.",
    "What drains your spirit drains your body. What fuels your spirit fuels your body.",
    "Invest in yourself. It pays the best interest.",
    "The best project you'll ever work on is you.",
    "Self-care means giving the world the best of you instead of what's left of you.",
    "Sometimes the bravest thing you can do is take care of yourself.",
    "You don't have to be perfect to be amazing.",
    "Kindness to yourself compounds just like interest.",
    "Your effort matters more than you know.",

    // ── TRACKING & ACCOUNTABILITY (401-430) ──────────────────
    "What gets measured gets managed.",
    "Tracking your progress is the fastest way to improve.",
    "If you can't measure it, you can't improve it.",
    "Data beats feelings. Track your way to success.",
    "Your journal is your most powerful tool.",
    "The simple act of writing it down makes you more committed.",
    "You can't change what you don't track.",
    "Awareness is the greatest agent for change.",
    "What you track improves. What you measure compounds.",
    "Track the process, not just the outcome.",
    "Journaling your progress is self-care in action.",
    "Self-awareness is the first step of change.",
    "Every accomplishment begins with the decision to keep track.",
    "Logging daily keeps you honest.",
    "Accountability is the glue that ties commitment to the result.",
    "You either make yourself accountable, or you will be made accountable.",
    "The pen is mightier than the excuse.",
    "Success is a series of small wins.",
    "Celebrate small wins.",
    "Don't wait until you reach your goal to be proud. Be proud of every step.",
    "Be proud of how far you've come. Have faith in how far you can go.",
    "Acknowledge what you've done. Celebrate what you've achieved. Envision what comes next.",
    "I celebrate my progress every single day.",
    "Every healthy decision is a vote for the life I want.",
    "Don't let perfect be the enemy of good.",
    "A workout is a personal triumph over laziness and procrastination.",
    "Building new habits takes time. Give yourself grace.",
    "The way you start your morning sets the tone for the rest of your day.",
    "Win the morning, win the day.",
    "Today I choose joy.",

    // ── WISDOM & PERSPECTIVE (431-470) ───────────────────────
    "Difficult roads often lead to beautiful destinations.",
    "Life is like riding a bicycle. To keep your balance, you must keep moving.",
    "The best view comes after the hardest climb.",
    "No rain, no flowers.",
    "Everything works out in the end. If it hasn't worked out, it's not the end.",
    "Turn your wounds into wisdom.",
    "The expert in anything was once a beginner.",
    "Life isn't about finding yourself. It's about creating yourself.",
    "Your time is limited. Don't waste it living someone else's life.",
    "Happiness is not something ready made. It comes from your own actions.",
    "Happiness depends upon ourselves.",
    "The purpose of our lives is to be happy and healthy.",
    "Don't judge each day by the harvest you reap, but by the seeds you plant.",
    "May your choices reflect your hopes, not your fears.",
    "The power of imagination makes us infinite.",
    "Not all who wander are lost.",
    "The best revenge is massive success.",
    "Life is 10% what happens to you and 90% how you respond.",
    "Do the best you can until you know better. Then do better.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "Knowing yourself is the beginning of all wisdom.",
    "Act as if what you do makes a difference. It does.",
    "The only person you are destined to become is the person you decide to be.",
    "Happiness is when what you think, what you say, and what you do are in harmony.",
    "Everything has beauty, but not everyone sees it in themselves.",
    "The present moment is filled with joy and happiness. If you are attentive, you will see it.",
    "A smooth sea never made a skilled sailor.",
    "Storms make trees take deeper roots.",
    "Just when the caterpillar thought the world was ending, it became a butterfly.",
    "Be stubborn about your goals and flexible about your methods.",
    "Life shrinks or expands in proportion to one's courage.",
    "Saying no to something is saying yes to something else.",
    "One good habit leads to another.",
    "What you think, you become. What you feel, you attract. What you imagine, you create.",
    "Dare to live the life you have dreamed for yourself.",
    "Find what makes you come alive and do more of that.",
    "Stay close to anything that makes you glad you are alive.",
    "Be so positive that negative people don't want to be around you.",
    "Live each day as if your life had just begun.",

    // ── AFFIRMATIONS (471-500) ───────────────────────────────
    "I am strong. I am capable. I am unstoppable.",
    "My body is a temple, and I will treat it as such.",
    "I deserve to be healthy, happy, and whole.",
    "I am becoming the best version of myself.",
    "Each healthy choice I make is a gift to my future self.",
    "I release what no longer serves me.",
    "I honor my body with nutritious food and movement.",
    "I am worthy of achieving all my goals.",
    "I forgive myself for past mistakes and embrace the future.",
    "My potential to succeed is infinite.",
    "I am grateful for this body and what it can do.",
    "I attract health, wealth, and happiness.",
    "Today I will do my best, and that is enough.",
    "I am proud of myself for trying.",
    "I am in control of my health and happiness.",
    "I am resilient. I bounce back from setbacks.",
    "I trust the timing of my life.",
    "My goals are within reach.",
    "I am stronger today than I was yesterday.",
    "I am becoming healthier, one choice at a time.",
    "I choose discipline over regret.",
    "My efforts compound over time.",
    "I love the person I am becoming.",
    "I nurture my body, mind, and soul.",
    "I embrace challenges as opportunities for growth.",
    "I believe in myself and my ability to succeed.",
    "I am a work in progress and that's okay.",
    "My hard work will pay off.",
    "I am proof that change is possible.",
    "Today, I take one more step toward the life I deserve."
  ];

  const getRandom = () => ALL[Math.floor(Math.random() * ALL.length)];

  const getCount = () => ALL.length;

  return { getRandom, getCount, ALL };
})();
